### ISSUE TITLE
DAC Scan Analysis Failed

### ISSUE THREAD

**Issue by jjaramilloG** [cms-gem-daq-project/vfatqc-python-scripts#262]
## Running doQC7.sh -s 1 -a 6 -o 0x1 -c GE11-X-S-PAK-0005, I got this error message: 
```
====================
Analyzing VFAT3 DAC Scan Data
====================
Loading info from input TTree
An unexpected exception has occured: global name 'np' is not defined
global name 'np' is not defined
DAC Scan Analysis Failed
Conncetivity Testing Failed
Goodbye
```

### Types of issue

- [x] Bug report (report an issue with the code)

@bdorney

**Comment by bdorney** [comment]
Typically @jjaramilloG you should fill out *all* of the template sections instead of deleting them.

**Comment by bdorney** [comment]
The full strack trace is:

```bash
Traceback (most recent call last):
  File "/opt/cmsgemos/bin/testConnectivity.py", line 1210, in <module>
    testConnectivity(args)
  File "/opt/cmsgemos/bin/testConnectivity.py", line 871, in testConnectivity
    dacAnalysis(args, calTree.gemTree, chamber_config, scandate=startTime)
  File "/usr/lib/python2.7/site-packages/gempython/gemplotting/utils/anautilities.py", line 54, in dacAnalysis
    vfatIDArray = getSubArray(vfatArray, ['vfatID','vfatN'])
  File "/usr/lib/python2.7/site-packages/gempython/gemplotting/utils/anautilities.py", line 884, in getSubArray
    dtype2 = np.dtype({name:structArray.dtype.fields[name] for name in fields})
NameError: global name 'np' is not defined
```

This is in `gem-plotting-tools`.  Closing this issue and opening there.
